/*
LaunchDarkly REST API

Testing FlagImportConfigurationsBetaApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package ldapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/launchdarkly/api-client-go"
)

func Test_ldapi_FlagImportConfigurationsBetaApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FlagImportConfigurationsBetaApiService CreateFlagImportConfiguration", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectKey string
		var integrationKey string

		resp, httpRes, err := apiClient.FlagImportConfigurationsBetaApi.CreateFlagImportConfiguration(context.Background(), projectKey, integrationKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FlagImportConfigurationsBetaApiService DeleteFlagImportConfiguration", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectKey string
		var integrationKey string
		var integrationId string

		httpRes, err := apiClient.FlagImportConfigurationsBetaApi.DeleteFlagImportConfiguration(context.Background(), projectKey, integrationKey, integrationId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FlagImportConfigurationsBetaApiService GetFlagImportConfiguration", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectKey string
		var integrationKey string
		var integrationId string

		resp, httpRes, err := apiClient.FlagImportConfigurationsBetaApi.GetFlagImportConfiguration(context.Background(), projectKey, integrationKey, integrationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FlagImportConfigurationsBetaApiService GetFlagImportConfigurations", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FlagImportConfigurationsBetaApi.GetFlagImportConfigurations(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FlagImportConfigurationsBetaApiService PatchFlagImportConfiguration", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectKey string
		var integrationKey string
		var integrationId string

		resp, httpRes, err := apiClient.FlagImportConfigurationsBetaApi.PatchFlagImportConfiguration(context.Background(), projectKey, integrationKey, integrationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FlagImportConfigurationsBetaApiService TriggerFlagImportJob", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectKey string
		var integrationKey string
		var integrationId string

		httpRes, err := apiClient.FlagImportConfigurationsBetaApi.TriggerFlagImportJob(context.Background(), projectKey, integrationKey, integrationId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
