/*
LaunchDarkly REST API

Testing DataExportDestinationsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package ldapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/launchdarkly/api-client-go"
)

func Test_ldapi_DataExportDestinationsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DataExportDestinationsApiService DeleteDestination", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectKey string
		var environmentKey string
		var id string

		httpRes, err := apiClient.DataExportDestinationsApi.DeleteDestination(context.Background(), projectKey, environmentKey, id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DataExportDestinationsApiService GetDestination", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectKey string
		var environmentKey string
		var id string

		resp, httpRes, err := apiClient.DataExportDestinationsApi.GetDestination(context.Background(), projectKey, environmentKey, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DataExportDestinationsApiService GetDestinations", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DataExportDestinationsApi.GetDestinations(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DataExportDestinationsApiService PatchDestination", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectKey string
		var environmentKey string
		var id string

		resp, httpRes, err := apiClient.DataExportDestinationsApi.PatchDestination(context.Background(), projectKey, environmentKey, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DataExportDestinationsApiService PostDestination", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectKey string
		var environmentKey string

		resp, httpRes, err := apiClient.DataExportDestinationsApi.PostDestination(context.Background(), projectKey, environmentKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DataExportDestinationsApiService PostGenerateTrustPolicy", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projKey string
		var envKey string

		resp, httpRes, err := apiClient.DataExportDestinationsApi.PostGenerateTrustPolicy(context.Background(), projKey, envKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DataExportDestinationsApiService PostGenerateWarehouseDestinationKeyPair", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DataExportDestinationsApi.PostGenerateWarehouseDestinationKeyPair(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
