/*
LaunchDarkly REST API

Testing SDKKeysBetaApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package ldapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/launchdarkly/api-client-go"
)

func Test_ldapi_SDKKeysBetaApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SDKKeysBetaApiService DeleteSdkKeyByKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectKey string
		var environmentKey string
		var sdkKeyKey string

		httpRes, err := apiClient.SDKKeysBetaApi.DeleteSdkKeyByKey(context.Background(), projectKey, environmentKey, sdkKeyKey).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SDKKeysBetaApiService GetSdkKeyByKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectKey string
		var environmentKey string
		var sdkKeyKey string

		resp, httpRes, err := apiClient.SDKKeysBetaApi.GetSdkKeyByKey(context.Background(), projectKey, environmentKey, sdkKeyKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SDKKeysBetaApiService PatchSdkKeyByKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectKey string
		var environmentKey string
		var sdkKeyKey string

		resp, httpRes, err := apiClient.SDKKeysBetaApi.PatchSdkKeyByKey(context.Background(), projectKey, environmentKey, sdkKeyKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SDKKeysBetaApiService PostSdkKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectKey string
		var environmentKey string

		resp, httpRes, err := apiClient.SDKKeysBetaApi.PostSdkKey(context.Background(), projectKey, environmentKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
