/*
LaunchDarkly REST API

Testing ReleasePoliciesBetaApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package ldapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/launchdarkly/api-client-go"
)

func Test_ldapi_ReleasePoliciesBetaApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ReleasePoliciesBetaApiService DeleteReleasePolicy", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectKey string
		var policyKey string

		httpRes, err := apiClient.ReleasePoliciesBetaApi.DeleteReleasePolicy(context.Background(), projectKey, policyKey).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReleasePoliciesBetaApiService GetReleasePolicies", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectKey string

		resp, httpRes, err := apiClient.ReleasePoliciesBetaApi.GetReleasePolicies(context.Background(), projectKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReleasePoliciesBetaApiService GetReleasePolicy", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectKey string
		var policyKey string

		resp, httpRes, err := apiClient.ReleasePoliciesBetaApi.GetReleasePolicy(context.Background(), projectKey, policyKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReleasePoliciesBetaApiService PostReleasePoliciesOrder", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectKey string

		resp, httpRes, err := apiClient.ReleasePoliciesBetaApi.PostReleasePoliciesOrder(context.Background(), projectKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReleasePoliciesBetaApiService PostReleasePolicy", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectKey string

		resp, httpRes, err := apiClient.ReleasePoliciesBetaApi.PostReleasePolicy(context.Background(), projectKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ReleasePoliciesBetaApiService PutReleasePolicy", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectKey string
		var policyKey string

		resp, httpRes, err := apiClient.ReleasePoliciesBetaApi.PutReleasePolicy(context.Background(), projectKey, policyKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
