/* 
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Clause struct {

	Attribute string `json:"attribute,omitempty"`

	Op string `json:"op,omitempty"`

	Values []string `json:"values,omitempty"`

	Negate bool `json:"negate,omitempty"`
}
