/* 
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@launchdarkly.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type EnvironmentBody struct {

	Name string `json:"name"`

	Key string `json:"key"`

	// A color swatch (as an RGB hex value with no leading '#', e.g. C8C8C8)
	Color string `json:"color"`

	DefaultTtl float32 `json:"defaultTtl,omitempty"`
}
