/*
 * LaunchDarkly REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0
 * Contact: support@launchdarkly.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ldapi

import (
	"encoding/json"
)

// CustomRoleRep struct for CustomRoleRep
type CustomRoleRep struct {
	Links *map[string]InlineResponse200 `json:"_links,omitempty"`
	Name *string `json:"name,omitempty"`
	Key *string `json:"key,omitempty"`
	Description *string `json:"description,omitempty"`
	Id *string `json:"_id,omitempty"`
	Policy *[]StatementRep `json:"policy,omitempty"`
	Access *AccessRep `json:"_access,omitempty"`
}

// NewCustomRoleRep instantiates a new CustomRoleRep object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomRoleRep() *CustomRoleRep {
	this := CustomRoleRep{}
	return &this
}

// NewCustomRoleRepWithDefaults instantiates a new CustomRoleRep object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomRoleRepWithDefaults() *CustomRoleRep {
	this := CustomRoleRep{}
	return &this
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *CustomRoleRep) GetLinks() map[string]InlineResponse200 {
	if o == nil || o.Links == nil {
		var ret map[string]InlineResponse200
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomRoleRep) GetLinksOk() (*map[string]InlineResponse200, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *CustomRoleRep) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given map[string]InlineResponse200 and assigns it to the Links field.
func (o *CustomRoleRep) SetLinks(v map[string]InlineResponse200) {
	o.Links = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CustomRoleRep) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomRoleRep) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CustomRoleRep) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CustomRoleRep) SetName(v string) {
	o.Name = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *CustomRoleRep) GetKey() string {
	if o == nil || o.Key == nil {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomRoleRep) GetKeyOk() (*string, bool) {
	if o == nil || o.Key == nil {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *CustomRoleRep) HasKey() bool {
	if o != nil && o.Key != nil {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *CustomRoleRep) SetKey(v string) {
	o.Key = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CustomRoleRep) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomRoleRep) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CustomRoleRep) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CustomRoleRep) SetDescription(v string) {
	o.Description = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CustomRoleRep) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomRoleRep) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CustomRoleRep) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CustomRoleRep) SetId(v string) {
	o.Id = &v
}

// GetPolicy returns the Policy field value if set, zero value otherwise.
func (o *CustomRoleRep) GetPolicy() []StatementRep {
	if o == nil || o.Policy == nil {
		var ret []StatementRep
		return ret
	}
	return *o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomRoleRep) GetPolicyOk() (*[]StatementRep, bool) {
	if o == nil || o.Policy == nil {
		return nil, false
	}
	return o.Policy, true
}

// HasPolicy returns a boolean if a field has been set.
func (o *CustomRoleRep) HasPolicy() bool {
	if o != nil && o.Policy != nil {
		return true
	}

	return false
}

// SetPolicy gets a reference to the given []StatementRep and assigns it to the Policy field.
func (o *CustomRoleRep) SetPolicy(v []StatementRep) {
	o.Policy = &v
}

// GetAccess returns the Access field value if set, zero value otherwise.
func (o *CustomRoleRep) GetAccess() AccessRep {
	if o == nil || o.Access == nil {
		var ret AccessRep
		return ret
	}
	return *o.Access
}

// GetAccessOk returns a tuple with the Access field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomRoleRep) GetAccessOk() (*AccessRep, bool) {
	if o == nil || o.Access == nil {
		return nil, false
	}
	return o.Access, true
}

// HasAccess returns a boolean if a field has been set.
func (o *CustomRoleRep) HasAccess() bool {
	if o != nil && o.Access != nil {
		return true
	}

	return false
}

// SetAccess gets a reference to the given AccessRep and assigns it to the Access field.
func (o *CustomRoleRep) SetAccess(v AccessRep) {
	o.Access = &v
}

func (o CustomRoleRep) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Links != nil {
		toSerialize["_links"] = o.Links
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Key != nil {
		toSerialize["key"] = o.Key
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Id != nil {
		toSerialize["_id"] = o.Id
	}
	if o.Policy != nil {
		toSerialize["policy"] = o.Policy
	}
	if o.Access != nil {
		toSerialize["_access"] = o.Access
	}
	return json.Marshal(toSerialize)
}

type NullableCustomRoleRep struct {
	value *CustomRoleRep
	isSet bool
}

func (v NullableCustomRoleRep) Get() *CustomRoleRep {
	return v.value
}

func (v *NullableCustomRoleRep) Set(val *CustomRoleRep) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomRoleRep) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomRoleRep) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomRoleRep(val *CustomRoleRep) *NullableCustomRoleRep {
	return &NullableCustomRoleRep{value: val, isSet: true}
}

func (v NullableCustomRoleRep) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomRoleRep) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


