/*
 * LaunchDarkly REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0
 * Contact: support@launchdarkly.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ldapi

import (
	"encoding/json"
)

// FlagsPrerequisite struct for FlagsPrerequisite
type FlagsPrerequisite struct {
	Key *string `json:"key,omitempty"`
	Variation *int32 `json:"variation,omitempty"`
}

// NewFlagsPrerequisite instantiates a new FlagsPrerequisite object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlagsPrerequisite() *FlagsPrerequisite {
	this := FlagsPrerequisite{}
	return &this
}

// NewFlagsPrerequisiteWithDefaults instantiates a new FlagsPrerequisite object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlagsPrerequisiteWithDefaults() *FlagsPrerequisite {
	this := FlagsPrerequisite{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *FlagsPrerequisite) GetKey() string {
	if o == nil || o.Key == nil {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlagsPrerequisite) GetKeyOk() (*string, bool) {
	if o == nil || o.Key == nil {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *FlagsPrerequisite) HasKey() bool {
	if o != nil && o.Key != nil {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *FlagsPrerequisite) SetKey(v string) {
	o.Key = &v
}

// GetVariation returns the Variation field value if set, zero value otherwise.
func (o *FlagsPrerequisite) GetVariation() int32 {
	if o == nil || o.Variation == nil {
		var ret int32
		return ret
	}
	return *o.Variation
}

// GetVariationOk returns a tuple with the Variation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlagsPrerequisite) GetVariationOk() (*int32, bool) {
	if o == nil || o.Variation == nil {
		return nil, false
	}
	return o.Variation, true
}

// HasVariation returns a boolean if a field has been set.
func (o *FlagsPrerequisite) HasVariation() bool {
	if o != nil && o.Variation != nil {
		return true
	}

	return false
}

// SetVariation gets a reference to the given int32 and assigns it to the Variation field.
func (o *FlagsPrerequisite) SetVariation(v int32) {
	o.Variation = &v
}

func (o FlagsPrerequisite) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Key != nil {
		toSerialize["key"] = o.Key
	}
	if o.Variation != nil {
		toSerialize["variation"] = o.Variation
	}
	return json.Marshal(toSerialize)
}

type NullableFlagsPrerequisite struct {
	value *FlagsPrerequisite
	isSet bool
}

func (v NullableFlagsPrerequisite) Get() *FlagsPrerequisite {
	return v.value
}

func (v *NullableFlagsPrerequisite) Set(val *FlagsPrerequisite) {
	v.value = val
	v.isSet = true
}

func (v NullableFlagsPrerequisite) IsSet() bool {
	return v.isSet
}

func (v *NullableFlagsPrerequisite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlagsPrerequisite(val *FlagsPrerequisite) *NullableFlagsPrerequisite {
	return &NullableFlagsPrerequisite{value: val, isSet: true}
}

func (v NullableFlagsPrerequisite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlagsPrerequisite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


