/*
 * LaunchDarkly REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0
 * Contact: support@launchdarkly.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ldapi

import (
	"encoding/json"
)

// UserSettingsCollection struct for UserSettingsCollection
type UserSettingsCollection struct {
	Items *map[string]UserSettingsCollectionItems `json:"items,omitempty"`
	Links *map[string]InlineResponse200 `json:"_links,omitempty"`
}

// NewUserSettingsCollection instantiates a new UserSettingsCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserSettingsCollection() *UserSettingsCollection {
	this := UserSettingsCollection{}
	return &this
}

// NewUserSettingsCollectionWithDefaults instantiates a new UserSettingsCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserSettingsCollectionWithDefaults() *UserSettingsCollection {
	this := UserSettingsCollection{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *UserSettingsCollection) GetItems() map[string]UserSettingsCollectionItems {
	if o == nil || o.Items == nil {
		var ret map[string]UserSettingsCollectionItems
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsCollection) GetItemsOk() (*map[string]UserSettingsCollectionItems, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *UserSettingsCollection) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given map[string]UserSettingsCollectionItems and assigns it to the Items field.
func (o *UserSettingsCollection) SetItems(v map[string]UserSettingsCollectionItems) {
	o.Items = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *UserSettingsCollection) GetLinks() map[string]InlineResponse200 {
	if o == nil || o.Links == nil {
		var ret map[string]InlineResponse200
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserSettingsCollection) GetLinksOk() (*map[string]InlineResponse200, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *UserSettingsCollection) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given map[string]InlineResponse200 and assigns it to the Links field.
func (o *UserSettingsCollection) SetLinks(v map[string]InlineResponse200) {
	o.Links = &v
}

func (o UserSettingsCollection) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if o.Links != nil {
		toSerialize["_links"] = o.Links
	}
	return json.Marshal(toSerialize)
}

type NullableUserSettingsCollection struct {
	value *UserSettingsCollection
	isSet bool
}

func (v NullableUserSettingsCollection) Get() *UserSettingsCollection {
	return v.value
}

func (v *NullableUserSettingsCollection) Set(val *UserSettingsCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableUserSettingsCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableUserSettingsCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserSettingsCollection(val *UserSettingsCollection) *NullableUserSettingsCollection {
	return &NullableUserSettingsCollection{value: val, isSet: true}
}

func (v NullableUserSettingsCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserSettingsCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


