/*
 * LaunchDarkly REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0
 * Contact: support@launchdarkly.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ldapi

import (
	"encoding/json"
)

// ApiStatisticCollectionRep struct for ApiStatisticCollectionRep
type ApiStatisticCollectionRep struct {
	Flags *map[string][]map[string]interface{} `json:"flags,omitempty"`
	Links *map[string]InlineResponse200 `json:"_links,omitempty"`
}

// NewApiStatisticCollectionRep instantiates a new ApiStatisticCollectionRep object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiStatisticCollectionRep() *ApiStatisticCollectionRep {
	this := ApiStatisticCollectionRep{}
	return &this
}

// NewApiStatisticCollectionRepWithDefaults instantiates a new ApiStatisticCollectionRep object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiStatisticCollectionRepWithDefaults() *ApiStatisticCollectionRep {
	this := ApiStatisticCollectionRep{}
	return &this
}

// GetFlags returns the Flags field value if set, zero value otherwise.
func (o *ApiStatisticCollectionRep) GetFlags() map[string][]map[string]interface{} {
	if o == nil || o.Flags == nil {
		var ret map[string][]map[string]interface{}
		return ret
	}
	return *o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiStatisticCollectionRep) GetFlagsOk() (*map[string][]map[string]interface{}, bool) {
	if o == nil || o.Flags == nil {
		return nil, false
	}
	return o.Flags, true
}

// HasFlags returns a boolean if a field has been set.
func (o *ApiStatisticCollectionRep) HasFlags() bool {
	if o != nil && o.Flags != nil {
		return true
	}

	return false
}

// SetFlags gets a reference to the given map[string][]map[string]interface{} and assigns it to the Flags field.
func (o *ApiStatisticCollectionRep) SetFlags(v map[string][]map[string]interface{}) {
	o.Flags = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *ApiStatisticCollectionRep) GetLinks() map[string]InlineResponse200 {
	if o == nil || o.Links == nil {
		var ret map[string]InlineResponse200
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiStatisticCollectionRep) GetLinksOk() (*map[string]InlineResponse200, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *ApiStatisticCollectionRep) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given map[string]InlineResponse200 and assigns it to the Links field.
func (o *ApiStatisticCollectionRep) SetLinks(v map[string]InlineResponse200) {
	o.Links = &v
}

func (o ApiStatisticCollectionRep) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Flags != nil {
		toSerialize["flags"] = o.Flags
	}
	if o.Links != nil {
		toSerialize["_links"] = o.Links
	}
	return json.Marshal(toSerialize)
}

type NullableApiStatisticCollectionRep struct {
	value *ApiStatisticCollectionRep
	isSet bool
}

func (v NullableApiStatisticCollectionRep) Get() *ApiStatisticCollectionRep {
	return v.value
}

func (v *NullableApiStatisticCollectionRep) Set(val *ApiStatisticCollectionRep) {
	v.value = val
	v.isSet = true
}

func (v NullableApiStatisticCollectionRep) IsSet() bool {
	return v.isSet
}

func (v *NullableApiStatisticCollectionRep) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiStatisticCollectionRep(val *ApiStatisticCollectionRep) *NullableApiStatisticCollectionRep {
	return &NullableApiStatisticCollectionRep{value: val, isSet: true}
}

func (v NullableApiStatisticCollectionRep) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiStatisticCollectionRep) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


