/*
 * LaunchDarkly REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0
 * Contact: support@launchdarkly.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ldapi

import (
	"encoding/json"
)

// ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest struct for ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest
type ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest struct {
	Comment *string `json:"comment,omitempty"`
	Description *string `json:"description,omitempty"`
	NotifyMemberIds *[]string `json:"notifyMemberIds,omitempty"`
	Source *ApprovalsEndpointsSourceFlag `json:"source,omitempty"`
	IncludedActions *[]string `json:"includedActions,omitempty"`
	ExcludedActions *[]string `json:"excludedActions,omitempty"`
}

// NewApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest instantiates a new ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest() *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest {
	this := ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest{}
	return &this
}

// NewApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequestWithDefaults instantiates a new ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequestWithDefaults() *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest {
	this := ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest{}
	return &this
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) GetComment() string {
	if o == nil || o.Comment == nil {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) GetCommentOk() (*string, bool) {
	if o == nil || o.Comment == nil {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) HasComment() bool {
	if o != nil && o.Comment != nil {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) SetComment(v string) {
	o.Comment = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) SetDescription(v string) {
	o.Description = &v
}

// GetNotifyMemberIds returns the NotifyMemberIds field value if set, zero value otherwise.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) GetNotifyMemberIds() []string {
	if o == nil || o.NotifyMemberIds == nil {
		var ret []string
		return ret
	}
	return *o.NotifyMemberIds
}

// GetNotifyMemberIdsOk returns a tuple with the NotifyMemberIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) GetNotifyMemberIdsOk() (*[]string, bool) {
	if o == nil || o.NotifyMemberIds == nil {
		return nil, false
	}
	return o.NotifyMemberIds, true
}

// HasNotifyMemberIds returns a boolean if a field has been set.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) HasNotifyMemberIds() bool {
	if o != nil && o.NotifyMemberIds != nil {
		return true
	}

	return false
}

// SetNotifyMemberIds gets a reference to the given []string and assigns it to the NotifyMemberIds field.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) SetNotifyMemberIds(v []string) {
	o.NotifyMemberIds = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) GetSource() ApprovalsEndpointsSourceFlag {
	if o == nil || o.Source == nil {
		var ret ApprovalsEndpointsSourceFlag
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) GetSourceOk() (*ApprovalsEndpointsSourceFlag, bool) {
	if o == nil || o.Source == nil {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) HasSource() bool {
	if o != nil && o.Source != nil {
		return true
	}

	return false
}

// SetSource gets a reference to the given ApprovalsEndpointsSourceFlag and assigns it to the Source field.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) SetSource(v ApprovalsEndpointsSourceFlag) {
	o.Source = &v
}

// GetIncludedActions returns the IncludedActions field value if set, zero value otherwise.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) GetIncludedActions() []string {
	if o == nil || o.IncludedActions == nil {
		var ret []string
		return ret
	}
	return *o.IncludedActions
}

// GetIncludedActionsOk returns a tuple with the IncludedActions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) GetIncludedActionsOk() (*[]string, bool) {
	if o == nil || o.IncludedActions == nil {
		return nil, false
	}
	return o.IncludedActions, true
}

// HasIncludedActions returns a boolean if a field has been set.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) HasIncludedActions() bool {
	if o != nil && o.IncludedActions != nil {
		return true
	}

	return false
}

// SetIncludedActions gets a reference to the given []string and assigns it to the IncludedActions field.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) SetIncludedActions(v []string) {
	o.IncludedActions = &v
}

// GetExcludedActions returns the ExcludedActions field value if set, zero value otherwise.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) GetExcludedActions() []string {
	if o == nil || o.ExcludedActions == nil {
		var ret []string
		return ret
	}
	return *o.ExcludedActions
}

// GetExcludedActionsOk returns a tuple with the ExcludedActions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) GetExcludedActionsOk() (*[]string, bool) {
	if o == nil || o.ExcludedActions == nil {
		return nil, false
	}
	return o.ExcludedActions, true
}

// HasExcludedActions returns a boolean if a field has been set.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) HasExcludedActions() bool {
	if o != nil && o.ExcludedActions != nil {
		return true
	}

	return false
}

// SetExcludedActions gets a reference to the given []string and assigns it to the ExcludedActions field.
func (o *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) SetExcludedActions(v []string) {
	o.ExcludedActions = &v
}

func (o ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Comment != nil {
		toSerialize["comment"] = o.Comment
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.NotifyMemberIds != nil {
		toSerialize["notifyMemberIds"] = o.NotifyMemberIds
	}
	if o.Source != nil {
		toSerialize["source"] = o.Source
	}
	if o.IncludedActions != nil {
		toSerialize["includedActions"] = o.IncludedActions
	}
	if o.ExcludedActions != nil {
		toSerialize["excludedActions"] = o.ExcludedActions
	}
	return json.Marshal(toSerialize)
}

type NullableApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest struct {
	value *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest
	isSet bool
}

func (v NullableApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) Get() *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest {
	return v.value
}

func (v *NullableApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) Set(val *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest(val *ApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) *NullableApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest {
	return &NullableApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest{value: val, isSet: true}
}

func (v NullableApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApprovalsEndpointsCreateCopyFlagConfigApprovalRequestRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


