/*
 * LaunchDarkly REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0
 * Contact: support@launchdarkly.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ldapi

import (
	"encoding/json"
)

// StatementRep struct for StatementRep
type StatementRep struct {
	Resources *[]map[string]interface{} `json:"resources,omitempty"`
	NotResources *[]map[string]interface{} `json:"notResources,omitempty"`
	Actions *[]string `json:"actions,omitempty"`
	NotActions *[]string `json:"notActions,omitempty"`
	Effect *string `json:"effect,omitempty"`
}

// NewStatementRep instantiates a new StatementRep object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatementRep() *StatementRep {
	this := StatementRep{}
	return &this
}

// NewStatementRepWithDefaults instantiates a new StatementRep object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatementRepWithDefaults() *StatementRep {
	this := StatementRep{}
	return &this
}

// GetResources returns the Resources field value if set, zero value otherwise.
func (o *StatementRep) GetResources() []map[string]interface{} {
	if o == nil || o.Resources == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatementRep) GetResourcesOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.Resources == nil {
		return nil, false
	}
	return o.Resources, true
}

// HasResources returns a boolean if a field has been set.
func (o *StatementRep) HasResources() bool {
	if o != nil && o.Resources != nil {
		return true
	}

	return false
}

// SetResources gets a reference to the given []map[string]interface{} and assigns it to the Resources field.
func (o *StatementRep) SetResources(v []map[string]interface{}) {
	o.Resources = &v
}

// GetNotResources returns the NotResources field value if set, zero value otherwise.
func (o *StatementRep) GetNotResources() []map[string]interface{} {
	if o == nil || o.NotResources == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.NotResources
}

// GetNotResourcesOk returns a tuple with the NotResources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatementRep) GetNotResourcesOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.NotResources == nil {
		return nil, false
	}
	return o.NotResources, true
}

// HasNotResources returns a boolean if a field has been set.
func (o *StatementRep) HasNotResources() bool {
	if o != nil && o.NotResources != nil {
		return true
	}

	return false
}

// SetNotResources gets a reference to the given []map[string]interface{} and assigns it to the NotResources field.
func (o *StatementRep) SetNotResources(v []map[string]interface{}) {
	o.NotResources = &v
}

// GetActions returns the Actions field value if set, zero value otherwise.
func (o *StatementRep) GetActions() []string {
	if o == nil || o.Actions == nil {
		var ret []string
		return ret
	}
	return *o.Actions
}

// GetActionsOk returns a tuple with the Actions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatementRep) GetActionsOk() (*[]string, bool) {
	if o == nil || o.Actions == nil {
		return nil, false
	}
	return o.Actions, true
}

// HasActions returns a boolean if a field has been set.
func (o *StatementRep) HasActions() bool {
	if o != nil && o.Actions != nil {
		return true
	}

	return false
}

// SetActions gets a reference to the given []string and assigns it to the Actions field.
func (o *StatementRep) SetActions(v []string) {
	o.Actions = &v
}

// GetNotActions returns the NotActions field value if set, zero value otherwise.
func (o *StatementRep) GetNotActions() []string {
	if o == nil || o.NotActions == nil {
		var ret []string
		return ret
	}
	return *o.NotActions
}

// GetNotActionsOk returns a tuple with the NotActions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatementRep) GetNotActionsOk() (*[]string, bool) {
	if o == nil || o.NotActions == nil {
		return nil, false
	}
	return o.NotActions, true
}

// HasNotActions returns a boolean if a field has been set.
func (o *StatementRep) HasNotActions() bool {
	if o != nil && o.NotActions != nil {
		return true
	}

	return false
}

// SetNotActions gets a reference to the given []string and assigns it to the NotActions field.
func (o *StatementRep) SetNotActions(v []string) {
	o.NotActions = &v
}

// GetEffect returns the Effect field value if set, zero value otherwise.
func (o *StatementRep) GetEffect() string {
	if o == nil || o.Effect == nil {
		var ret string
		return ret
	}
	return *o.Effect
}

// GetEffectOk returns a tuple with the Effect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatementRep) GetEffectOk() (*string, bool) {
	if o == nil || o.Effect == nil {
		return nil, false
	}
	return o.Effect, true
}

// HasEffect returns a boolean if a field has been set.
func (o *StatementRep) HasEffect() bool {
	if o != nil && o.Effect != nil {
		return true
	}

	return false
}

// SetEffect gets a reference to the given string and assigns it to the Effect field.
func (o *StatementRep) SetEffect(v string) {
	o.Effect = &v
}

func (o StatementRep) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Resources != nil {
		toSerialize["resources"] = o.Resources
	}
	if o.NotResources != nil {
		toSerialize["notResources"] = o.NotResources
	}
	if o.Actions != nil {
		toSerialize["actions"] = o.Actions
	}
	if o.NotActions != nil {
		toSerialize["notActions"] = o.NotActions
	}
	if o.Effect != nil {
		toSerialize["effect"] = o.Effect
	}
	return json.Marshal(toSerialize)
}

type NullableStatementRep struct {
	value *StatementRep
	isSet bool
}

func (v NullableStatementRep) Get() *StatementRep {
	return v.value
}

func (v *NullableStatementRep) Set(val *StatementRep) {
	v.value = val
	v.isSet = true
}

func (v NullableStatementRep) IsSet() bool {
	return v.isSet
}

func (v *NullableStatementRep) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatementRep(val *StatementRep) *NullableStatementRep {
	return &NullableStatementRep{value: val, isSet: true}
}

func (v NullableStatementRep) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatementRep) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


