/*
 * LaunchDarkly REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0
 * Contact: support@launchdarkly.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ldapi

import (
	"encoding/json"
)

// AccessDeniedRep struct for AccessDeniedRep
type AccessDeniedRep struct {
	Action *string `json:"action,omitempty"`
	Reason *AccessDeniedReasonRep `json:"reason,omitempty"`
}

// NewAccessDeniedRep instantiates a new AccessDeniedRep object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessDeniedRep() *AccessDeniedRep {
	this := AccessDeniedRep{}
	return &this
}

// NewAccessDeniedRepWithDefaults instantiates a new AccessDeniedRep object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessDeniedRepWithDefaults() *AccessDeniedRep {
	this := AccessDeniedRep{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *AccessDeniedRep) GetAction() string {
	if o == nil || o.Action == nil {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessDeniedRep) GetActionOk() (*string, bool) {
	if o == nil || o.Action == nil {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *AccessDeniedRep) HasAction() bool {
	if o != nil && o.Action != nil {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *AccessDeniedRep) SetAction(v string) {
	o.Action = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *AccessDeniedRep) GetReason() AccessDeniedReasonRep {
	if o == nil || o.Reason == nil {
		var ret AccessDeniedReasonRep
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessDeniedRep) GetReasonOk() (*AccessDeniedReasonRep, bool) {
	if o == nil || o.Reason == nil {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *AccessDeniedRep) HasReason() bool {
	if o != nil && o.Reason != nil {
		return true
	}

	return false
}

// SetReason gets a reference to the given AccessDeniedReasonRep and assigns it to the Reason field.
func (o *AccessDeniedRep) SetReason(v AccessDeniedReasonRep) {
	o.Reason = &v
}

func (o AccessDeniedRep) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Action != nil {
		toSerialize["action"] = o.Action
	}
	if o.Reason != nil {
		toSerialize["reason"] = o.Reason
	}
	return json.Marshal(toSerialize)
}

type NullableAccessDeniedRep struct {
	value *AccessDeniedRep
	isSet bool
}

func (v NullableAccessDeniedRep) Get() *AccessDeniedRep {
	return v.value
}

func (v *NullableAccessDeniedRep) Set(val *AccessDeniedRep) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessDeniedRep) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessDeniedRep) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessDeniedRep(val *AccessDeniedRep) *NullableAccessDeniedRep {
	return &NullableAccessDeniedRep{value: val, isSet: true}
}

func (v NullableAccessDeniedRep) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessDeniedRep) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


