/*
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * API version: 3.9.2
 * Contact: support@launchdarkly.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package ldapi

type UnboundedSegmentTargetsBody struct {
	Included *UnboundedSegmentTargetChanges `json:"included,omitempty"`
	Excluded *UnboundedSegmentTargetChanges `json:"excluded,omitempty"`
}
