/*
 * LaunchDarkly REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0
 * Contact: support@launchdarkly.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ldapi

import (
	"encoding/json"
)

// AccessTokensAccessTokenPost struct for AccessTokensAccessTokenPost
type AccessTokensAccessTokenPost struct {
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Role *string `json:"role,omitempty"`
	CustomRoleIds *[]string `json:"customRoleIds,omitempty"`
	InlineRole *[]AccessTokensAccessTokenPostInlineRole `json:"inlineRole,omitempty"`
	ServiceToken *bool `json:"serviceToken,omitempty"`
	DefaultApiVersion *int32 `json:"defaultApiVersion,omitempty"`
}

// NewAccessTokensAccessTokenPost instantiates a new AccessTokensAccessTokenPost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessTokensAccessTokenPost() *AccessTokensAccessTokenPost {
	this := AccessTokensAccessTokenPost{}
	return &this
}

// NewAccessTokensAccessTokenPostWithDefaults instantiates a new AccessTokensAccessTokenPost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessTokensAccessTokenPostWithDefaults() *AccessTokensAccessTokenPost {
	this := AccessTokensAccessTokenPost{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AccessTokensAccessTokenPost) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessTokensAccessTokenPost) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AccessTokensAccessTokenPost) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AccessTokensAccessTokenPost) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AccessTokensAccessTokenPost) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessTokensAccessTokenPost) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AccessTokensAccessTokenPost) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AccessTokensAccessTokenPost) SetDescription(v string) {
	o.Description = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *AccessTokensAccessTokenPost) GetRole() string {
	if o == nil || o.Role == nil {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessTokensAccessTokenPost) GetRoleOk() (*string, bool) {
	if o == nil || o.Role == nil {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *AccessTokensAccessTokenPost) HasRole() bool {
	if o != nil && o.Role != nil {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *AccessTokensAccessTokenPost) SetRole(v string) {
	o.Role = &v
}

// GetCustomRoleIds returns the CustomRoleIds field value if set, zero value otherwise.
func (o *AccessTokensAccessTokenPost) GetCustomRoleIds() []string {
	if o == nil || o.CustomRoleIds == nil {
		var ret []string
		return ret
	}
	return *o.CustomRoleIds
}

// GetCustomRoleIdsOk returns a tuple with the CustomRoleIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessTokensAccessTokenPost) GetCustomRoleIdsOk() (*[]string, bool) {
	if o == nil || o.CustomRoleIds == nil {
		return nil, false
	}
	return o.CustomRoleIds, true
}

// HasCustomRoleIds returns a boolean if a field has been set.
func (o *AccessTokensAccessTokenPost) HasCustomRoleIds() bool {
	if o != nil && o.CustomRoleIds != nil {
		return true
	}

	return false
}

// SetCustomRoleIds gets a reference to the given []string and assigns it to the CustomRoleIds field.
func (o *AccessTokensAccessTokenPost) SetCustomRoleIds(v []string) {
	o.CustomRoleIds = &v
}

// GetInlineRole returns the InlineRole field value if set, zero value otherwise.
func (o *AccessTokensAccessTokenPost) GetInlineRole() []AccessTokensAccessTokenPostInlineRole {
	if o == nil || o.InlineRole == nil {
		var ret []AccessTokensAccessTokenPostInlineRole
		return ret
	}
	return *o.InlineRole
}

// GetInlineRoleOk returns a tuple with the InlineRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessTokensAccessTokenPost) GetInlineRoleOk() (*[]AccessTokensAccessTokenPostInlineRole, bool) {
	if o == nil || o.InlineRole == nil {
		return nil, false
	}
	return o.InlineRole, true
}

// HasInlineRole returns a boolean if a field has been set.
func (o *AccessTokensAccessTokenPost) HasInlineRole() bool {
	if o != nil && o.InlineRole != nil {
		return true
	}

	return false
}

// SetInlineRole gets a reference to the given []AccessTokensAccessTokenPostInlineRole and assigns it to the InlineRole field.
func (o *AccessTokensAccessTokenPost) SetInlineRole(v []AccessTokensAccessTokenPostInlineRole) {
	o.InlineRole = &v
}

// GetServiceToken returns the ServiceToken field value if set, zero value otherwise.
func (o *AccessTokensAccessTokenPost) GetServiceToken() bool {
	if o == nil || o.ServiceToken == nil {
		var ret bool
		return ret
	}
	return *o.ServiceToken
}

// GetServiceTokenOk returns a tuple with the ServiceToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessTokensAccessTokenPost) GetServiceTokenOk() (*bool, bool) {
	if o == nil || o.ServiceToken == nil {
		return nil, false
	}
	return o.ServiceToken, true
}

// HasServiceToken returns a boolean if a field has been set.
func (o *AccessTokensAccessTokenPost) HasServiceToken() bool {
	if o != nil && o.ServiceToken != nil {
		return true
	}

	return false
}

// SetServiceToken gets a reference to the given bool and assigns it to the ServiceToken field.
func (o *AccessTokensAccessTokenPost) SetServiceToken(v bool) {
	o.ServiceToken = &v
}

// GetDefaultApiVersion returns the DefaultApiVersion field value if set, zero value otherwise.
func (o *AccessTokensAccessTokenPost) GetDefaultApiVersion() int32 {
	if o == nil || o.DefaultApiVersion == nil {
		var ret int32
		return ret
	}
	return *o.DefaultApiVersion
}

// GetDefaultApiVersionOk returns a tuple with the DefaultApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessTokensAccessTokenPost) GetDefaultApiVersionOk() (*int32, bool) {
	if o == nil || o.DefaultApiVersion == nil {
		return nil, false
	}
	return o.DefaultApiVersion, true
}

// HasDefaultApiVersion returns a boolean if a field has been set.
func (o *AccessTokensAccessTokenPost) HasDefaultApiVersion() bool {
	if o != nil && o.DefaultApiVersion != nil {
		return true
	}

	return false
}

// SetDefaultApiVersion gets a reference to the given int32 and assigns it to the DefaultApiVersion field.
func (o *AccessTokensAccessTokenPost) SetDefaultApiVersion(v int32) {
	o.DefaultApiVersion = &v
}

func (o AccessTokensAccessTokenPost) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Role != nil {
		toSerialize["role"] = o.Role
	}
	if o.CustomRoleIds != nil {
		toSerialize["customRoleIds"] = o.CustomRoleIds
	}
	if o.InlineRole != nil {
		toSerialize["inlineRole"] = o.InlineRole
	}
	if o.ServiceToken != nil {
		toSerialize["serviceToken"] = o.ServiceToken
	}
	if o.DefaultApiVersion != nil {
		toSerialize["defaultApiVersion"] = o.DefaultApiVersion
	}
	return json.Marshal(toSerialize)
}

type NullableAccessTokensAccessTokenPost struct {
	value *AccessTokensAccessTokenPost
	isSet bool
}

func (v NullableAccessTokensAccessTokenPost) Get() *AccessTokensAccessTokenPost {
	return v.value
}

func (v *NullableAccessTokensAccessTokenPost) Set(val *AccessTokensAccessTokenPost) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessTokensAccessTokenPost) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessTokensAccessTokenPost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessTokensAccessTokenPost(val *AccessTokensAccessTokenPost) *NullableAccessTokensAccessTokenPost {
	return &NullableAccessTokensAccessTokenPost{value: val, isSet: true}
}

func (v NullableAccessTokensAccessTokenPost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessTokensAccessTokenPost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


