/*
 * LaunchDarkly REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0
 * Contact: support@launchdarkly.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ldapi

import (
	"encoding/json"
)

// WebConflictResponseConflicts struct for WebConflictResponseConflicts
type WebConflictResponseConflicts struct {
	Id *string `json:"_id,omitempty"`
	Reason *string `json:"reason,omitempty"`
	PendingChangeWillFail *bool `json:"pendingChangeWillFail,omitempty"`
}

// NewWebConflictResponseConflicts instantiates a new WebConflictResponseConflicts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebConflictResponseConflicts() *WebConflictResponseConflicts {
	this := WebConflictResponseConflicts{}
	return &this
}

// NewWebConflictResponseConflictsWithDefaults instantiates a new WebConflictResponseConflicts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebConflictResponseConflictsWithDefaults() *WebConflictResponseConflicts {
	this := WebConflictResponseConflicts{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *WebConflictResponseConflicts) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebConflictResponseConflicts) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *WebConflictResponseConflicts) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *WebConflictResponseConflicts) SetId(v string) {
	o.Id = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *WebConflictResponseConflicts) GetReason() string {
	if o == nil || o.Reason == nil {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebConflictResponseConflicts) GetReasonOk() (*string, bool) {
	if o == nil || o.Reason == nil {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *WebConflictResponseConflicts) HasReason() bool {
	if o != nil && o.Reason != nil {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *WebConflictResponseConflicts) SetReason(v string) {
	o.Reason = &v
}

// GetPendingChangeWillFail returns the PendingChangeWillFail field value if set, zero value otherwise.
func (o *WebConflictResponseConflicts) GetPendingChangeWillFail() bool {
	if o == nil || o.PendingChangeWillFail == nil {
		var ret bool
		return ret
	}
	return *o.PendingChangeWillFail
}

// GetPendingChangeWillFailOk returns a tuple with the PendingChangeWillFail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebConflictResponseConflicts) GetPendingChangeWillFailOk() (*bool, bool) {
	if o == nil || o.PendingChangeWillFail == nil {
		return nil, false
	}
	return o.PendingChangeWillFail, true
}

// HasPendingChangeWillFail returns a boolean if a field has been set.
func (o *WebConflictResponseConflicts) HasPendingChangeWillFail() bool {
	if o != nil && o.PendingChangeWillFail != nil {
		return true
	}

	return false
}

// SetPendingChangeWillFail gets a reference to the given bool and assigns it to the PendingChangeWillFail field.
func (o *WebConflictResponseConflicts) SetPendingChangeWillFail(v bool) {
	o.PendingChangeWillFail = &v
}

func (o WebConflictResponseConflicts) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["_id"] = o.Id
	}
	if o.Reason != nil {
		toSerialize["reason"] = o.Reason
	}
	if o.PendingChangeWillFail != nil {
		toSerialize["pendingChangeWillFail"] = o.PendingChangeWillFail
	}
	return json.Marshal(toSerialize)
}

type NullableWebConflictResponseConflicts struct {
	value *WebConflictResponseConflicts
	isSet bool
}

func (v NullableWebConflictResponseConflicts) Get() *WebConflictResponseConflicts {
	return v.value
}

func (v *NullableWebConflictResponseConflicts) Set(val *WebConflictResponseConflicts) {
	v.value = val
	v.isSet = true
}

func (v NullableWebConflictResponseConflicts) IsSet() bool {
	return v.isSet
}

func (v *NullableWebConflictResponseConflicts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebConflictResponseConflicts(val *WebConflictResponseConflicts) *NullableWebConflictResponseConflicts {
	return &NullableWebConflictResponseConflicts{value: val, isSet: true}
}

func (v NullableWebConflictResponseConflicts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebConflictResponseConflicts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


