/*
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * API version: 3.10.0
 * Contact: support@launchdarkly.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package ldapi

type Integrations struct {
	// A mapping of integration types to their respective API endpoints.
	Links *interface{} `json:"_links,omitempty"`
	Items []IntegrationSubscription `json:"items,omitempty"`
}
