/*
 * LaunchDarkly REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0
 * Contact: support@launchdarkly.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ldapi

import (
	"encoding/json"
)

// MetricRep struct for MetricRep
type MetricRep struct {
	Id *string `json:"_id,omitempty"`
	Key *string `json:"key,omitempty"`
	Name *string `json:"name,omitempty"`
	Kind *string `json:"kind,omitempty"`
	AttachedFlagCount *int32 `json:"_attachedFlagCount,omitempty"`
	Links *map[string]InlineResponse200 `json:"_links,omitempty"`
	Site *CoreLink `json:"_site,omitempty"`
	Access *AccessRep `json:"_access,omitempty"`
	Tags *[]string `json:"tags,omitempty"`
	CreationDate *int64 `json:"_creationDate,omitempty"`
	LastModified *GoalsModification `json:"lastModified,omitempty"`
	MaintainerId *string `json:"maintainerId,omitempty"`
	Maintainer *MemberSummaryRep `json:"_maintainer,omitempty"`
	Description *string `json:"description,omitempty"`
	IsNumeric *bool `json:"isNumeric,omitempty"`
	SuccessCriteria *int32 `json:"successCriteria,omitempty"`
	Unit *string `json:"unit,omitempty"`
	EventKey *string `json:"eventKey,omitempty"`
	IsActive *bool `json:"isActive,omitempty"`
	AttachedFeatures *[]DependentFlagWithEnvsEnvironments `json:"_attachedFeatures,omitempty"`
	Version *int32 `json:"_version,omitempty"`
	Selector *string `json:"selector,omitempty"`
	Urls *[]interface{} `json:"urls,omitempty"`
}

// NewMetricRep instantiates a new MetricRep object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetricRep() *MetricRep {
	this := MetricRep{}
	return &this
}

// NewMetricRepWithDefaults instantiates a new MetricRep object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetricRepWithDefaults() *MetricRep {
	this := MetricRep{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MetricRep) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricRep) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MetricRep) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MetricRep) SetId(v string) {
	o.Id = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *MetricRep) GetKey() string {
	if o == nil || o.Key == nil {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricRep) GetKeyOk() (*string, bool) {
	if o == nil || o.Key == nil {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *MetricRep) HasKey() bool {
	if o != nil && o.Key != nil {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *MetricRep) SetKey(v string) {
	o.Key = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MetricRep) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricRep) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MetricRep) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MetricRep) SetName(v string) {
	o.Name = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *MetricRep) GetKind() string {
	if o == nil || o.Kind == nil {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricRep) GetKindOk() (*string, bool) {
	if o == nil || o.Kind == nil {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *MetricRep) HasKind() bool {
	if o != nil && o.Kind != nil {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *MetricRep) SetKind(v string) {
	o.Kind = &v
}

// GetAttachedFlagCount returns the AttachedFlagCount field value if set, zero value otherwise.
func (o *MetricRep) GetAttachedFlagCount() int32 {
	if o == nil || o.AttachedFlagCount == nil {
		var ret int32
		return ret
	}
	return *o.AttachedFlagCount
}

// GetAttachedFlagCountOk returns a tuple with the AttachedFlagCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricRep) GetAttachedFlagCountOk() (*int32, bool) {
	if o == nil || o.AttachedFlagCount == nil {
		return nil, false
	}
	return o.AttachedFlagCount, true
}

// HasAttachedFlagCount returns a boolean if a field has been set.
func (o *MetricRep) HasAttachedFlagCount() bool {
	if o != nil && o.AttachedFlagCount != nil {
		return true
	}

	return false
}

// SetAttachedFlagCount gets a reference to the given int32 and assigns it to the AttachedFlagCount field.
func (o *MetricRep) SetAttachedFlagCount(v int32) {
	o.AttachedFlagCount = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *MetricRep) GetLinks() map[string]InlineResponse200 {
	if o == nil || o.Links == nil {
		var ret map[string]InlineResponse200
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricRep) GetLinksOk() (*map[string]InlineResponse200, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *MetricRep) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given map[string]InlineResponse200 and assigns it to the Links field.
func (o *MetricRep) SetLinks(v map[string]InlineResponse200) {
	o.Links = &v
}

// GetSite returns the Site field value if set, zero value otherwise.
func (o *MetricRep) GetSite() CoreLink {
	if o == nil || o.Site == nil {
		var ret CoreLink
		return ret
	}
	return *o.Site
}

// GetSiteOk returns a tuple with the Site field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricRep) GetSiteOk() (*CoreLink, bool) {
	if o == nil || o.Site == nil {
		return nil, false
	}
	return o.Site, true
}

// HasSite returns a boolean if a field has been set.
func (o *MetricRep) HasSite() bool {
	if o != nil && o.Site != nil {
		return true
	}

	return false
}

// SetSite gets a reference to the given CoreLink and assigns it to the Site field.
func (o *MetricRep) SetSite(v CoreLink) {
	o.Site = &v
}

// GetAccess returns the Access field value if set, zero value otherwise.
func (o *MetricRep) GetAccess() AccessRep {
	if o == nil || o.Access == nil {
		var ret AccessRep
		return ret
	}
	return *o.Access
}

// GetAccessOk returns a tuple with the Access field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricRep) GetAccessOk() (*AccessRep, bool) {
	if o == nil || o.Access == nil {
		return nil, false
	}
	return o.Access, true
}

// HasAccess returns a boolean if a field has been set.
func (o *MetricRep) HasAccess() bool {
	if o != nil && o.Access != nil {
		return true
	}

	return false
}

// SetAccess gets a reference to the given AccessRep and assigns it to the Access field.
func (o *MetricRep) SetAccess(v AccessRep) {
	o.Access = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *MetricRep) GetTags() []string {
	if o == nil || o.Tags == nil {
		var ret []string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricRep) GetTagsOk() (*[]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *MetricRep) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *MetricRep) SetTags(v []string) {
	o.Tags = &v
}

// GetCreationDate returns the CreationDate field value if set, zero value otherwise.
func (o *MetricRep) GetCreationDate() int64 {
	if o == nil || o.CreationDate == nil {
		var ret int64
		return ret
	}
	return *o.CreationDate
}

// GetCreationDateOk returns a tuple with the CreationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricRep) GetCreationDateOk() (*int64, bool) {
	if o == nil || o.CreationDate == nil {
		return nil, false
	}
	return o.CreationDate, true
}

// HasCreationDate returns a boolean if a field has been set.
func (o *MetricRep) HasCreationDate() bool {
	if o != nil && o.CreationDate != nil {
		return true
	}

	return false
}

// SetCreationDate gets a reference to the given int64 and assigns it to the CreationDate field.
func (o *MetricRep) SetCreationDate(v int64) {
	o.CreationDate = &v
}

// GetLastModified returns the LastModified field value if set, zero value otherwise.
func (o *MetricRep) GetLastModified() GoalsModification {
	if o == nil || o.LastModified == nil {
		var ret GoalsModification
		return ret
	}
	return *o.LastModified
}

// GetLastModifiedOk returns a tuple with the LastModified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricRep) GetLastModifiedOk() (*GoalsModification, bool) {
	if o == nil || o.LastModified == nil {
		return nil, false
	}
	return o.LastModified, true
}

// HasLastModified returns a boolean if a field has been set.
func (o *MetricRep) HasLastModified() bool {
	if o != nil && o.LastModified != nil {
		return true
	}

	return false
}

// SetLastModified gets a reference to the given GoalsModification and assigns it to the LastModified field.
func (o *MetricRep) SetLastModified(v GoalsModification) {
	o.LastModified = &v
}

// GetMaintainerId returns the MaintainerId field value if set, zero value otherwise.
func (o *MetricRep) GetMaintainerId() string {
	if o == nil || o.MaintainerId == nil {
		var ret string
		return ret
	}
	return *o.MaintainerId
}

// GetMaintainerIdOk returns a tuple with the MaintainerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricRep) GetMaintainerIdOk() (*string, bool) {
	if o == nil || o.MaintainerId == nil {
		return nil, false
	}
	return o.MaintainerId, true
}

// HasMaintainerId returns a boolean if a field has been set.
func (o *MetricRep) HasMaintainerId() bool {
	if o != nil && o.MaintainerId != nil {
		return true
	}

	return false
}

// SetMaintainerId gets a reference to the given string and assigns it to the MaintainerId field.
func (o *MetricRep) SetMaintainerId(v string) {
	o.MaintainerId = &v
}

// GetMaintainer returns the Maintainer field value if set, zero value otherwise.
func (o *MetricRep) GetMaintainer() MemberSummaryRep {
	if o == nil || o.Maintainer == nil {
		var ret MemberSummaryRep
		return ret
	}
	return *o.Maintainer
}

// GetMaintainerOk returns a tuple with the Maintainer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricRep) GetMaintainerOk() (*MemberSummaryRep, bool) {
	if o == nil || o.Maintainer == nil {
		return nil, false
	}
	return o.Maintainer, true
}

// HasMaintainer returns a boolean if a field has been set.
func (o *MetricRep) HasMaintainer() bool {
	if o != nil && o.Maintainer != nil {
		return true
	}

	return false
}

// SetMaintainer gets a reference to the given MemberSummaryRep and assigns it to the Maintainer field.
func (o *MetricRep) SetMaintainer(v MemberSummaryRep) {
	o.Maintainer = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *MetricRep) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricRep) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *MetricRep) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *MetricRep) SetDescription(v string) {
	o.Description = &v
}

// GetIsNumeric returns the IsNumeric field value if set, zero value otherwise.
func (o *MetricRep) GetIsNumeric() bool {
	if o == nil || o.IsNumeric == nil {
		var ret bool
		return ret
	}
	return *o.IsNumeric
}

// GetIsNumericOk returns a tuple with the IsNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricRep) GetIsNumericOk() (*bool, bool) {
	if o == nil || o.IsNumeric == nil {
		return nil, false
	}
	return o.IsNumeric, true
}

// HasIsNumeric returns a boolean if a field has been set.
func (o *MetricRep) HasIsNumeric() bool {
	if o != nil && o.IsNumeric != nil {
		return true
	}

	return false
}

// SetIsNumeric gets a reference to the given bool and assigns it to the IsNumeric field.
func (o *MetricRep) SetIsNumeric(v bool) {
	o.IsNumeric = &v
}

// GetSuccessCriteria returns the SuccessCriteria field value if set, zero value otherwise.
func (o *MetricRep) GetSuccessCriteria() int32 {
	if o == nil || o.SuccessCriteria == nil {
		var ret int32
		return ret
	}
	return *o.SuccessCriteria
}

// GetSuccessCriteriaOk returns a tuple with the SuccessCriteria field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricRep) GetSuccessCriteriaOk() (*int32, bool) {
	if o == nil || o.SuccessCriteria == nil {
		return nil, false
	}
	return o.SuccessCriteria, true
}

// HasSuccessCriteria returns a boolean if a field has been set.
func (o *MetricRep) HasSuccessCriteria() bool {
	if o != nil && o.SuccessCriteria != nil {
		return true
	}

	return false
}

// SetSuccessCriteria gets a reference to the given int32 and assigns it to the SuccessCriteria field.
func (o *MetricRep) SetSuccessCriteria(v int32) {
	o.SuccessCriteria = &v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *MetricRep) GetUnit() string {
	if o == nil || o.Unit == nil {
		var ret string
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricRep) GetUnitOk() (*string, bool) {
	if o == nil || o.Unit == nil {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *MetricRep) HasUnit() bool {
	if o != nil && o.Unit != nil {
		return true
	}

	return false
}

// SetUnit gets a reference to the given string and assigns it to the Unit field.
func (o *MetricRep) SetUnit(v string) {
	o.Unit = &v
}

// GetEventKey returns the EventKey field value if set, zero value otherwise.
func (o *MetricRep) GetEventKey() string {
	if o == nil || o.EventKey == nil {
		var ret string
		return ret
	}
	return *o.EventKey
}

// GetEventKeyOk returns a tuple with the EventKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricRep) GetEventKeyOk() (*string, bool) {
	if o == nil || o.EventKey == nil {
		return nil, false
	}
	return o.EventKey, true
}

// HasEventKey returns a boolean if a field has been set.
func (o *MetricRep) HasEventKey() bool {
	if o != nil && o.EventKey != nil {
		return true
	}

	return false
}

// SetEventKey gets a reference to the given string and assigns it to the EventKey field.
func (o *MetricRep) SetEventKey(v string) {
	o.EventKey = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *MetricRep) GetIsActive() bool {
	if o == nil || o.IsActive == nil {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricRep) GetIsActiveOk() (*bool, bool) {
	if o == nil || o.IsActive == nil {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *MetricRep) HasIsActive() bool {
	if o != nil && o.IsActive != nil {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *MetricRep) SetIsActive(v bool) {
	o.IsActive = &v
}

// GetAttachedFeatures returns the AttachedFeatures field value if set, zero value otherwise.
func (o *MetricRep) GetAttachedFeatures() []DependentFlagWithEnvsEnvironments {
	if o == nil || o.AttachedFeatures == nil {
		var ret []DependentFlagWithEnvsEnvironments
		return ret
	}
	return *o.AttachedFeatures
}

// GetAttachedFeaturesOk returns a tuple with the AttachedFeatures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricRep) GetAttachedFeaturesOk() (*[]DependentFlagWithEnvsEnvironments, bool) {
	if o == nil || o.AttachedFeatures == nil {
		return nil, false
	}
	return o.AttachedFeatures, true
}

// HasAttachedFeatures returns a boolean if a field has been set.
func (o *MetricRep) HasAttachedFeatures() bool {
	if o != nil && o.AttachedFeatures != nil {
		return true
	}

	return false
}

// SetAttachedFeatures gets a reference to the given []DependentFlagWithEnvsEnvironments and assigns it to the AttachedFeatures field.
func (o *MetricRep) SetAttachedFeatures(v []DependentFlagWithEnvsEnvironments) {
	o.AttachedFeatures = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *MetricRep) GetVersion() int32 {
	if o == nil || o.Version == nil {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricRep) GetVersionOk() (*int32, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *MetricRep) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *MetricRep) SetVersion(v int32) {
	o.Version = &v
}

// GetSelector returns the Selector field value if set, zero value otherwise.
func (o *MetricRep) GetSelector() string {
	if o == nil || o.Selector == nil {
		var ret string
		return ret
	}
	return *o.Selector
}

// GetSelectorOk returns a tuple with the Selector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricRep) GetSelectorOk() (*string, bool) {
	if o == nil || o.Selector == nil {
		return nil, false
	}
	return o.Selector, true
}

// HasSelector returns a boolean if a field has been set.
func (o *MetricRep) HasSelector() bool {
	if o != nil && o.Selector != nil {
		return true
	}

	return false
}

// SetSelector gets a reference to the given string and assigns it to the Selector field.
func (o *MetricRep) SetSelector(v string) {
	o.Selector = &v
}

// GetUrls returns the Urls field value if set, zero value otherwise.
func (o *MetricRep) GetUrls() []interface{} {
	if o == nil || o.Urls == nil {
		var ret []interface{}
		return ret
	}
	return *o.Urls
}

// GetUrlsOk returns a tuple with the Urls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricRep) GetUrlsOk() (*[]interface{}, bool) {
	if o == nil || o.Urls == nil {
		return nil, false
	}
	return o.Urls, true
}

// HasUrls returns a boolean if a field has been set.
func (o *MetricRep) HasUrls() bool {
	if o != nil && o.Urls != nil {
		return true
	}

	return false
}

// SetUrls gets a reference to the given []interface{} and assigns it to the Urls field.
func (o *MetricRep) SetUrls(v []interface{}) {
	o.Urls = &v
}

func (o MetricRep) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["_id"] = o.Id
	}
	if o.Key != nil {
		toSerialize["key"] = o.Key
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Kind != nil {
		toSerialize["kind"] = o.Kind
	}
	if o.AttachedFlagCount != nil {
		toSerialize["_attachedFlagCount"] = o.AttachedFlagCount
	}
	if o.Links != nil {
		toSerialize["_links"] = o.Links
	}
	if o.Site != nil {
		toSerialize["_site"] = o.Site
	}
	if o.Access != nil {
		toSerialize["_access"] = o.Access
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.CreationDate != nil {
		toSerialize["_creationDate"] = o.CreationDate
	}
	if o.LastModified != nil {
		toSerialize["lastModified"] = o.LastModified
	}
	if o.MaintainerId != nil {
		toSerialize["maintainerId"] = o.MaintainerId
	}
	if o.Maintainer != nil {
		toSerialize["_maintainer"] = o.Maintainer
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.IsNumeric != nil {
		toSerialize["isNumeric"] = o.IsNumeric
	}
	if o.SuccessCriteria != nil {
		toSerialize["successCriteria"] = o.SuccessCriteria
	}
	if o.Unit != nil {
		toSerialize["unit"] = o.Unit
	}
	if o.EventKey != nil {
		toSerialize["eventKey"] = o.EventKey
	}
	if o.IsActive != nil {
		toSerialize["isActive"] = o.IsActive
	}
	if o.AttachedFeatures != nil {
		toSerialize["_attachedFeatures"] = o.AttachedFeatures
	}
	if o.Version != nil {
		toSerialize["_version"] = o.Version
	}
	if o.Selector != nil {
		toSerialize["selector"] = o.Selector
	}
	if o.Urls != nil {
		toSerialize["urls"] = o.Urls
	}
	return json.Marshal(toSerialize)
}

type NullableMetricRep struct {
	value *MetricRep
	isSet bool
}

func (v NullableMetricRep) Get() *MetricRep {
	return v.value
}

func (v *NullableMetricRep) Set(val *MetricRep) {
	v.value = val
	v.isSet = true
}

func (v NullableMetricRep) IsSet() bool {
	return v.isSet
}

func (v *NullableMetricRep) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetricRep(val *MetricRep) *NullableMetricRep {
	return &NullableMetricRep{value: val, isSet: true}
}

func (v NullableMetricRep) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetricRep) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


