/*
 * LaunchDarkly REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0
 * Contact: support@launchdarkly.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ldapi

import (
	"encoding/json"
	"time"
)

// ModelsDerivedAttribute struct for ModelsDerivedAttribute
type ModelsDerivedAttribute struct {
	Value interface{} `json:"value,omitempty"`
	LastDerived *time.Time `json:"lastDerived,omitempty"`
}

// NewModelsDerivedAttribute instantiates a new ModelsDerivedAttribute object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsDerivedAttribute() *ModelsDerivedAttribute {
	this := ModelsDerivedAttribute{}
	return &this
}

// NewModelsDerivedAttributeWithDefaults instantiates a new ModelsDerivedAttribute object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsDerivedAttributeWithDefaults() *ModelsDerivedAttribute {
	this := ModelsDerivedAttribute{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelsDerivedAttribute) GetValue() interface{} {
	if o == nil  {
		var ret interface{}
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelsDerivedAttribute) GetValueOk() (*interface{}, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return &o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ModelsDerivedAttribute) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given interface{} and assigns it to the Value field.
func (o *ModelsDerivedAttribute) SetValue(v interface{}) {
	o.Value = v
}

// GetLastDerived returns the LastDerived field value if set, zero value otherwise.
func (o *ModelsDerivedAttribute) GetLastDerived() time.Time {
	if o == nil || o.LastDerived == nil {
		var ret time.Time
		return ret
	}
	return *o.LastDerived
}

// GetLastDerivedOk returns a tuple with the LastDerived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsDerivedAttribute) GetLastDerivedOk() (*time.Time, bool) {
	if o == nil || o.LastDerived == nil {
		return nil, false
	}
	return o.LastDerived, true
}

// HasLastDerived returns a boolean if a field has been set.
func (o *ModelsDerivedAttribute) HasLastDerived() bool {
	if o != nil && o.LastDerived != nil {
		return true
	}

	return false
}

// SetLastDerived gets a reference to the given time.Time and assigns it to the LastDerived field.
func (o *ModelsDerivedAttribute) SetLastDerived(v time.Time) {
	o.LastDerived = &v
}

func (o ModelsDerivedAttribute) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	if o.LastDerived != nil {
		toSerialize["lastDerived"] = o.LastDerived
	}
	return json.Marshal(toSerialize)
}

type NullableModelsDerivedAttribute struct {
	value *ModelsDerivedAttribute
	isSet bool
}

func (v NullableModelsDerivedAttribute) Get() *ModelsDerivedAttribute {
	return v.value
}

func (v *NullableModelsDerivedAttribute) Set(val *ModelsDerivedAttribute) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsDerivedAttribute) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsDerivedAttribute) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsDerivedAttribute(val *ModelsDerivedAttribute) *NullableModelsDerivedAttribute {
	return &NullableModelsDerivedAttribute{value: val, isSet: true}
}

func (v NullableModelsDerivedAttribute) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsDerivedAttribute) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


