/*
 * LaunchDarkly REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0
 * Contact: support@launchdarkly.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ldapi

import (
	"encoding/json"
)

// GlobalFlagCollectionRep struct for GlobalFlagCollectionRep
type GlobalFlagCollectionRep struct {
	Items *[]GlobalFlagRep `json:"items,omitempty"`
	Links *map[string]InlineResponse200 `json:"_links,omitempty"`
	TotalCount *int32 `json:"totalCount,omitempty"`
}

// NewGlobalFlagCollectionRep instantiates a new GlobalFlagCollectionRep object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGlobalFlagCollectionRep() *GlobalFlagCollectionRep {
	this := GlobalFlagCollectionRep{}
	return &this
}

// NewGlobalFlagCollectionRepWithDefaults instantiates a new GlobalFlagCollectionRep object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGlobalFlagCollectionRepWithDefaults() *GlobalFlagCollectionRep {
	this := GlobalFlagCollectionRep{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *GlobalFlagCollectionRep) GetItems() []GlobalFlagRep {
	if o == nil || o.Items == nil {
		var ret []GlobalFlagRep
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GlobalFlagCollectionRep) GetItemsOk() (*[]GlobalFlagRep, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *GlobalFlagCollectionRep) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []GlobalFlagRep and assigns it to the Items field.
func (o *GlobalFlagCollectionRep) SetItems(v []GlobalFlagRep) {
	o.Items = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *GlobalFlagCollectionRep) GetLinks() map[string]InlineResponse200 {
	if o == nil || o.Links == nil {
		var ret map[string]InlineResponse200
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GlobalFlagCollectionRep) GetLinksOk() (*map[string]InlineResponse200, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *GlobalFlagCollectionRep) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given map[string]InlineResponse200 and assigns it to the Links field.
func (o *GlobalFlagCollectionRep) SetLinks(v map[string]InlineResponse200) {
	o.Links = &v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *GlobalFlagCollectionRep) GetTotalCount() int32 {
	if o == nil || o.TotalCount == nil {
		var ret int32
		return ret
	}
	return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GlobalFlagCollectionRep) GetTotalCountOk() (*int32, bool) {
	if o == nil || o.TotalCount == nil {
		return nil, false
	}
	return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *GlobalFlagCollectionRep) HasTotalCount() bool {
	if o != nil && o.TotalCount != nil {
		return true
	}

	return false
}

// SetTotalCount gets a reference to the given int32 and assigns it to the TotalCount field.
func (o *GlobalFlagCollectionRep) SetTotalCount(v int32) {
	o.TotalCount = &v
}

func (o GlobalFlagCollectionRep) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if o.Links != nil {
		toSerialize["_links"] = o.Links
	}
	if o.TotalCount != nil {
		toSerialize["totalCount"] = o.TotalCount
	}
	return json.Marshal(toSerialize)
}

type NullableGlobalFlagCollectionRep struct {
	value *GlobalFlagCollectionRep
	isSet bool
}

func (v NullableGlobalFlagCollectionRep) Get() *GlobalFlagCollectionRep {
	return v.value
}

func (v *NullableGlobalFlagCollectionRep) Set(val *GlobalFlagCollectionRep) {
	v.value = val
	v.isSet = true
}

func (v NullableGlobalFlagCollectionRep) IsSet() bool {
	return v.isSet
}

func (v *NullableGlobalFlagCollectionRep) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGlobalFlagCollectionRep(val *GlobalFlagCollectionRep) *NullableGlobalFlagCollectionRep {
	return &NullableGlobalFlagCollectionRep{value: val, isSet: true}
}

func (v NullableGlobalFlagCollectionRep) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGlobalFlagCollectionRep) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


