/*
 * LaunchDarkly REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0
 * Contact: support@launchdarkly.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ldapi

import (
	"encoding/json"
)

// ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest struct for ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest
type ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest struct {
	Comment *string `json:"comment,omitempty"`
	Description *string `json:"description,omitempty"`
	Instructions *[]map[string]interface{} `json:"instructions,omitempty"`
	NotifyMemberIds *[]string `json:"notifyMemberIds,omitempty"`
	ExecutionDate *int64 `json:"executionDate,omitempty"`
	OperatingOnId *string `json:"operatingOnId,omitempty"`
}

// NewApprovalsEndpointsCreateFlagConfigApprovalRequestRequest instantiates a new ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApprovalsEndpointsCreateFlagConfigApprovalRequestRequest() *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest {
	this := ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest{}
	return &this
}

// NewApprovalsEndpointsCreateFlagConfigApprovalRequestRequestWithDefaults instantiates a new ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApprovalsEndpointsCreateFlagConfigApprovalRequestRequestWithDefaults() *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest {
	this := ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest{}
	return &this
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) GetComment() string {
	if o == nil || o.Comment == nil {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) GetCommentOk() (*string, bool) {
	if o == nil || o.Comment == nil {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) HasComment() bool {
	if o != nil && o.Comment != nil {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) SetComment(v string) {
	o.Comment = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) SetDescription(v string) {
	o.Description = &v
}

// GetInstructions returns the Instructions field value if set, zero value otherwise.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) GetInstructions() []map[string]interface{} {
	if o == nil || o.Instructions == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.Instructions
}

// GetInstructionsOk returns a tuple with the Instructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) GetInstructionsOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.Instructions == nil {
		return nil, false
	}
	return o.Instructions, true
}

// HasInstructions returns a boolean if a field has been set.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) HasInstructions() bool {
	if o != nil && o.Instructions != nil {
		return true
	}

	return false
}

// SetInstructions gets a reference to the given []map[string]interface{} and assigns it to the Instructions field.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) SetInstructions(v []map[string]interface{}) {
	o.Instructions = &v
}

// GetNotifyMemberIds returns the NotifyMemberIds field value if set, zero value otherwise.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) GetNotifyMemberIds() []string {
	if o == nil || o.NotifyMemberIds == nil {
		var ret []string
		return ret
	}
	return *o.NotifyMemberIds
}

// GetNotifyMemberIdsOk returns a tuple with the NotifyMemberIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) GetNotifyMemberIdsOk() (*[]string, bool) {
	if o == nil || o.NotifyMemberIds == nil {
		return nil, false
	}
	return o.NotifyMemberIds, true
}

// HasNotifyMemberIds returns a boolean if a field has been set.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) HasNotifyMemberIds() bool {
	if o != nil && o.NotifyMemberIds != nil {
		return true
	}

	return false
}

// SetNotifyMemberIds gets a reference to the given []string and assigns it to the NotifyMemberIds field.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) SetNotifyMemberIds(v []string) {
	o.NotifyMemberIds = &v
}

// GetExecutionDate returns the ExecutionDate field value if set, zero value otherwise.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) GetExecutionDate() int64 {
	if o == nil || o.ExecutionDate == nil {
		var ret int64
		return ret
	}
	return *o.ExecutionDate
}

// GetExecutionDateOk returns a tuple with the ExecutionDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) GetExecutionDateOk() (*int64, bool) {
	if o == nil || o.ExecutionDate == nil {
		return nil, false
	}
	return o.ExecutionDate, true
}

// HasExecutionDate returns a boolean if a field has been set.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) HasExecutionDate() bool {
	if o != nil && o.ExecutionDate != nil {
		return true
	}

	return false
}

// SetExecutionDate gets a reference to the given int64 and assigns it to the ExecutionDate field.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) SetExecutionDate(v int64) {
	o.ExecutionDate = &v
}

// GetOperatingOnId returns the OperatingOnId field value if set, zero value otherwise.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) GetOperatingOnId() string {
	if o == nil || o.OperatingOnId == nil {
		var ret string
		return ret
	}
	return *o.OperatingOnId
}

// GetOperatingOnIdOk returns a tuple with the OperatingOnId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) GetOperatingOnIdOk() (*string, bool) {
	if o == nil || o.OperatingOnId == nil {
		return nil, false
	}
	return o.OperatingOnId, true
}

// HasOperatingOnId returns a boolean if a field has been set.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) HasOperatingOnId() bool {
	if o != nil && o.OperatingOnId != nil {
		return true
	}

	return false
}

// SetOperatingOnId gets a reference to the given string and assigns it to the OperatingOnId field.
func (o *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) SetOperatingOnId(v string) {
	o.OperatingOnId = &v
}

func (o ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Comment != nil {
		toSerialize["comment"] = o.Comment
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Instructions != nil {
		toSerialize["instructions"] = o.Instructions
	}
	if o.NotifyMemberIds != nil {
		toSerialize["notifyMemberIds"] = o.NotifyMemberIds
	}
	if o.ExecutionDate != nil {
		toSerialize["executionDate"] = o.ExecutionDate
	}
	if o.OperatingOnId != nil {
		toSerialize["operatingOnId"] = o.OperatingOnId
	}
	return json.Marshal(toSerialize)
}

type NullableApprovalsEndpointsCreateFlagConfigApprovalRequestRequest struct {
	value *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest
	isSet bool
}

func (v NullableApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) Get() *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest {
	return v.value
}

func (v *NullableApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) Set(val *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApprovalsEndpointsCreateFlagConfigApprovalRequestRequest(val *ApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) *NullableApprovalsEndpointsCreateFlagConfigApprovalRequestRequest {
	return &NullableApprovalsEndpointsCreateFlagConfigApprovalRequestRequest{value: val, isSet: true}
}

func (v NullableApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApprovalsEndpointsCreateFlagConfigApprovalRequestRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


