/*
 * LaunchDarkly REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0
 * Contact: support@launchdarkly.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ldapi

import (
	"encoding/json"
)

// ExpiringUserTargetsEndpointsPatchSegmentRequest struct for ExpiringUserTargetsEndpointsPatchSegmentRequest
type ExpiringUserTargetsEndpointsPatchSegmentRequest struct {
	Comment *string `json:"comment,omitempty"`
	Instructions *[]ExpiringUserTargetsEndpointsPatchSegmentRequestInstructions `json:"instructions,omitempty"`
}

// NewExpiringUserTargetsEndpointsPatchSegmentRequest instantiates a new ExpiringUserTargetsEndpointsPatchSegmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpiringUserTargetsEndpointsPatchSegmentRequest() *ExpiringUserTargetsEndpointsPatchSegmentRequest {
	this := ExpiringUserTargetsEndpointsPatchSegmentRequest{}
	return &this
}

// NewExpiringUserTargetsEndpointsPatchSegmentRequestWithDefaults instantiates a new ExpiringUserTargetsEndpointsPatchSegmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpiringUserTargetsEndpointsPatchSegmentRequestWithDefaults() *ExpiringUserTargetsEndpointsPatchSegmentRequest {
	this := ExpiringUserTargetsEndpointsPatchSegmentRequest{}
	return &this
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *ExpiringUserTargetsEndpointsPatchSegmentRequest) GetComment() string {
	if o == nil || o.Comment == nil {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpiringUserTargetsEndpointsPatchSegmentRequest) GetCommentOk() (*string, bool) {
	if o == nil || o.Comment == nil {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *ExpiringUserTargetsEndpointsPatchSegmentRequest) HasComment() bool {
	if o != nil && o.Comment != nil {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *ExpiringUserTargetsEndpointsPatchSegmentRequest) SetComment(v string) {
	o.Comment = &v
}

// GetInstructions returns the Instructions field value if set, zero value otherwise.
func (o *ExpiringUserTargetsEndpointsPatchSegmentRequest) GetInstructions() []ExpiringUserTargetsEndpointsPatchSegmentRequestInstructions {
	if o == nil || o.Instructions == nil {
		var ret []ExpiringUserTargetsEndpointsPatchSegmentRequestInstructions
		return ret
	}
	return *o.Instructions
}

// GetInstructionsOk returns a tuple with the Instructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpiringUserTargetsEndpointsPatchSegmentRequest) GetInstructionsOk() (*[]ExpiringUserTargetsEndpointsPatchSegmentRequestInstructions, bool) {
	if o == nil || o.Instructions == nil {
		return nil, false
	}
	return o.Instructions, true
}

// HasInstructions returns a boolean if a field has been set.
func (o *ExpiringUserTargetsEndpointsPatchSegmentRequest) HasInstructions() bool {
	if o != nil && o.Instructions != nil {
		return true
	}

	return false
}

// SetInstructions gets a reference to the given []ExpiringUserTargetsEndpointsPatchSegmentRequestInstructions and assigns it to the Instructions field.
func (o *ExpiringUserTargetsEndpointsPatchSegmentRequest) SetInstructions(v []ExpiringUserTargetsEndpointsPatchSegmentRequestInstructions) {
	o.Instructions = &v
}

func (o ExpiringUserTargetsEndpointsPatchSegmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Comment != nil {
		toSerialize["comment"] = o.Comment
	}
	if o.Instructions != nil {
		toSerialize["instructions"] = o.Instructions
	}
	return json.Marshal(toSerialize)
}

type NullableExpiringUserTargetsEndpointsPatchSegmentRequest struct {
	value *ExpiringUserTargetsEndpointsPatchSegmentRequest
	isSet bool
}

func (v NullableExpiringUserTargetsEndpointsPatchSegmentRequest) Get() *ExpiringUserTargetsEndpointsPatchSegmentRequest {
	return v.value
}

func (v *NullableExpiringUserTargetsEndpointsPatchSegmentRequest) Set(val *ExpiringUserTargetsEndpointsPatchSegmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExpiringUserTargetsEndpointsPatchSegmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExpiringUserTargetsEndpointsPatchSegmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpiringUserTargetsEndpointsPatchSegmentRequest(val *ExpiringUserTargetsEndpointsPatchSegmentRequest) *NullableExpiringUserTargetsEndpointsPatchSegmentRequest {
	return &NullableExpiringUserTargetsEndpointsPatchSegmentRequest{value: val, isSet: true}
}

func (v NullableExpiringUserTargetsEndpointsPatchSegmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpiringUserTargetsEndpointsPatchSegmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


