/*
 * LaunchDarkly REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0
 * Contact: support@launchdarkly.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ldapi

import (
	"encoding/json"
)

// MetricListingRep struct for MetricListingRep
type MetricListingRep struct {
	Id *string `json:"_id,omitempty"`
	Key *string `json:"key,omitempty"`
	Name *string `json:"name,omitempty"`
	Kind *string `json:"kind,omitempty"`
	AttachedFlagCount *int32 `json:"_attachedFlagCount,omitempty"`
	Links *map[string]InlineResponse200 `json:"_links,omitempty"`
	Site *CoreLink `json:"_site,omitempty"`
	Access *AccessRep `json:"_access,omitempty"`
	Tags *[]string `json:"tags,omitempty"`
	CreationDate *int64 `json:"_creationDate,omitempty"`
	LastModified *GoalsModification `json:"lastModified,omitempty"`
	MaintainerId *string `json:"maintainerId,omitempty"`
	Maintainer *MemberSummaryRep `json:"_maintainer,omitempty"`
	Description *string `json:"description,omitempty"`
	IsNumeric *bool `json:"isNumeric,omitempty"`
	SuccessCriteria *int32 `json:"successCriteria,omitempty"`
	Unit *string `json:"unit,omitempty"`
	EventKey *string `json:"eventKey,omitempty"`
}

// NewMetricListingRep instantiates a new MetricListingRep object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetricListingRep() *MetricListingRep {
	this := MetricListingRep{}
	return &this
}

// NewMetricListingRepWithDefaults instantiates a new MetricListingRep object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetricListingRepWithDefaults() *MetricListingRep {
	this := MetricListingRep{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MetricListingRep) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricListingRep) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MetricListingRep) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MetricListingRep) SetId(v string) {
	o.Id = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *MetricListingRep) GetKey() string {
	if o == nil || o.Key == nil {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricListingRep) GetKeyOk() (*string, bool) {
	if o == nil || o.Key == nil {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *MetricListingRep) HasKey() bool {
	if o != nil && o.Key != nil {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *MetricListingRep) SetKey(v string) {
	o.Key = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MetricListingRep) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricListingRep) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MetricListingRep) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MetricListingRep) SetName(v string) {
	o.Name = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *MetricListingRep) GetKind() string {
	if o == nil || o.Kind == nil {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricListingRep) GetKindOk() (*string, bool) {
	if o == nil || o.Kind == nil {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *MetricListingRep) HasKind() bool {
	if o != nil && o.Kind != nil {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *MetricListingRep) SetKind(v string) {
	o.Kind = &v
}

// GetAttachedFlagCount returns the AttachedFlagCount field value if set, zero value otherwise.
func (o *MetricListingRep) GetAttachedFlagCount() int32 {
	if o == nil || o.AttachedFlagCount == nil {
		var ret int32
		return ret
	}
	return *o.AttachedFlagCount
}

// GetAttachedFlagCountOk returns a tuple with the AttachedFlagCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricListingRep) GetAttachedFlagCountOk() (*int32, bool) {
	if o == nil || o.AttachedFlagCount == nil {
		return nil, false
	}
	return o.AttachedFlagCount, true
}

// HasAttachedFlagCount returns a boolean if a field has been set.
func (o *MetricListingRep) HasAttachedFlagCount() bool {
	if o != nil && o.AttachedFlagCount != nil {
		return true
	}

	return false
}

// SetAttachedFlagCount gets a reference to the given int32 and assigns it to the AttachedFlagCount field.
func (o *MetricListingRep) SetAttachedFlagCount(v int32) {
	o.AttachedFlagCount = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *MetricListingRep) GetLinks() map[string]InlineResponse200 {
	if o == nil || o.Links == nil {
		var ret map[string]InlineResponse200
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricListingRep) GetLinksOk() (*map[string]InlineResponse200, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *MetricListingRep) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given map[string]InlineResponse200 and assigns it to the Links field.
func (o *MetricListingRep) SetLinks(v map[string]InlineResponse200) {
	o.Links = &v
}

// GetSite returns the Site field value if set, zero value otherwise.
func (o *MetricListingRep) GetSite() CoreLink {
	if o == nil || o.Site == nil {
		var ret CoreLink
		return ret
	}
	return *o.Site
}

// GetSiteOk returns a tuple with the Site field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricListingRep) GetSiteOk() (*CoreLink, bool) {
	if o == nil || o.Site == nil {
		return nil, false
	}
	return o.Site, true
}

// HasSite returns a boolean if a field has been set.
func (o *MetricListingRep) HasSite() bool {
	if o != nil && o.Site != nil {
		return true
	}

	return false
}

// SetSite gets a reference to the given CoreLink and assigns it to the Site field.
func (o *MetricListingRep) SetSite(v CoreLink) {
	o.Site = &v
}

// GetAccess returns the Access field value if set, zero value otherwise.
func (o *MetricListingRep) GetAccess() AccessRep {
	if o == nil || o.Access == nil {
		var ret AccessRep
		return ret
	}
	return *o.Access
}

// GetAccessOk returns a tuple with the Access field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricListingRep) GetAccessOk() (*AccessRep, bool) {
	if o == nil || o.Access == nil {
		return nil, false
	}
	return o.Access, true
}

// HasAccess returns a boolean if a field has been set.
func (o *MetricListingRep) HasAccess() bool {
	if o != nil && o.Access != nil {
		return true
	}

	return false
}

// SetAccess gets a reference to the given AccessRep and assigns it to the Access field.
func (o *MetricListingRep) SetAccess(v AccessRep) {
	o.Access = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *MetricListingRep) GetTags() []string {
	if o == nil || o.Tags == nil {
		var ret []string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricListingRep) GetTagsOk() (*[]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *MetricListingRep) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *MetricListingRep) SetTags(v []string) {
	o.Tags = &v
}

// GetCreationDate returns the CreationDate field value if set, zero value otherwise.
func (o *MetricListingRep) GetCreationDate() int64 {
	if o == nil || o.CreationDate == nil {
		var ret int64
		return ret
	}
	return *o.CreationDate
}

// GetCreationDateOk returns a tuple with the CreationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricListingRep) GetCreationDateOk() (*int64, bool) {
	if o == nil || o.CreationDate == nil {
		return nil, false
	}
	return o.CreationDate, true
}

// HasCreationDate returns a boolean if a field has been set.
func (o *MetricListingRep) HasCreationDate() bool {
	if o != nil && o.CreationDate != nil {
		return true
	}

	return false
}

// SetCreationDate gets a reference to the given int64 and assigns it to the CreationDate field.
func (o *MetricListingRep) SetCreationDate(v int64) {
	o.CreationDate = &v
}

// GetLastModified returns the LastModified field value if set, zero value otherwise.
func (o *MetricListingRep) GetLastModified() GoalsModification {
	if o == nil || o.LastModified == nil {
		var ret GoalsModification
		return ret
	}
	return *o.LastModified
}

// GetLastModifiedOk returns a tuple with the LastModified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricListingRep) GetLastModifiedOk() (*GoalsModification, bool) {
	if o == nil || o.LastModified == nil {
		return nil, false
	}
	return o.LastModified, true
}

// HasLastModified returns a boolean if a field has been set.
func (o *MetricListingRep) HasLastModified() bool {
	if o != nil && o.LastModified != nil {
		return true
	}

	return false
}

// SetLastModified gets a reference to the given GoalsModification and assigns it to the LastModified field.
func (o *MetricListingRep) SetLastModified(v GoalsModification) {
	o.LastModified = &v
}

// GetMaintainerId returns the MaintainerId field value if set, zero value otherwise.
func (o *MetricListingRep) GetMaintainerId() string {
	if o == nil || o.MaintainerId == nil {
		var ret string
		return ret
	}
	return *o.MaintainerId
}

// GetMaintainerIdOk returns a tuple with the MaintainerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricListingRep) GetMaintainerIdOk() (*string, bool) {
	if o == nil || o.MaintainerId == nil {
		return nil, false
	}
	return o.MaintainerId, true
}

// HasMaintainerId returns a boolean if a field has been set.
func (o *MetricListingRep) HasMaintainerId() bool {
	if o != nil && o.MaintainerId != nil {
		return true
	}

	return false
}

// SetMaintainerId gets a reference to the given string and assigns it to the MaintainerId field.
func (o *MetricListingRep) SetMaintainerId(v string) {
	o.MaintainerId = &v
}

// GetMaintainer returns the Maintainer field value if set, zero value otherwise.
func (o *MetricListingRep) GetMaintainer() MemberSummaryRep {
	if o == nil || o.Maintainer == nil {
		var ret MemberSummaryRep
		return ret
	}
	return *o.Maintainer
}

// GetMaintainerOk returns a tuple with the Maintainer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricListingRep) GetMaintainerOk() (*MemberSummaryRep, bool) {
	if o == nil || o.Maintainer == nil {
		return nil, false
	}
	return o.Maintainer, true
}

// HasMaintainer returns a boolean if a field has been set.
func (o *MetricListingRep) HasMaintainer() bool {
	if o != nil && o.Maintainer != nil {
		return true
	}

	return false
}

// SetMaintainer gets a reference to the given MemberSummaryRep and assigns it to the Maintainer field.
func (o *MetricListingRep) SetMaintainer(v MemberSummaryRep) {
	o.Maintainer = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *MetricListingRep) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricListingRep) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *MetricListingRep) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *MetricListingRep) SetDescription(v string) {
	o.Description = &v
}

// GetIsNumeric returns the IsNumeric field value if set, zero value otherwise.
func (o *MetricListingRep) GetIsNumeric() bool {
	if o == nil || o.IsNumeric == nil {
		var ret bool
		return ret
	}
	return *o.IsNumeric
}

// GetIsNumericOk returns a tuple with the IsNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricListingRep) GetIsNumericOk() (*bool, bool) {
	if o == nil || o.IsNumeric == nil {
		return nil, false
	}
	return o.IsNumeric, true
}

// HasIsNumeric returns a boolean if a field has been set.
func (o *MetricListingRep) HasIsNumeric() bool {
	if o != nil && o.IsNumeric != nil {
		return true
	}

	return false
}

// SetIsNumeric gets a reference to the given bool and assigns it to the IsNumeric field.
func (o *MetricListingRep) SetIsNumeric(v bool) {
	o.IsNumeric = &v
}

// GetSuccessCriteria returns the SuccessCriteria field value if set, zero value otherwise.
func (o *MetricListingRep) GetSuccessCriteria() int32 {
	if o == nil || o.SuccessCriteria == nil {
		var ret int32
		return ret
	}
	return *o.SuccessCriteria
}

// GetSuccessCriteriaOk returns a tuple with the SuccessCriteria field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricListingRep) GetSuccessCriteriaOk() (*int32, bool) {
	if o == nil || o.SuccessCriteria == nil {
		return nil, false
	}
	return o.SuccessCriteria, true
}

// HasSuccessCriteria returns a boolean if a field has been set.
func (o *MetricListingRep) HasSuccessCriteria() bool {
	if o != nil && o.SuccessCriteria != nil {
		return true
	}

	return false
}

// SetSuccessCriteria gets a reference to the given int32 and assigns it to the SuccessCriteria field.
func (o *MetricListingRep) SetSuccessCriteria(v int32) {
	o.SuccessCriteria = &v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *MetricListingRep) GetUnit() string {
	if o == nil || o.Unit == nil {
		var ret string
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricListingRep) GetUnitOk() (*string, bool) {
	if o == nil || o.Unit == nil {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *MetricListingRep) HasUnit() bool {
	if o != nil && o.Unit != nil {
		return true
	}

	return false
}

// SetUnit gets a reference to the given string and assigns it to the Unit field.
func (o *MetricListingRep) SetUnit(v string) {
	o.Unit = &v
}

// GetEventKey returns the EventKey field value if set, zero value otherwise.
func (o *MetricListingRep) GetEventKey() string {
	if o == nil || o.EventKey == nil {
		var ret string
		return ret
	}
	return *o.EventKey
}

// GetEventKeyOk returns a tuple with the EventKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricListingRep) GetEventKeyOk() (*string, bool) {
	if o == nil || o.EventKey == nil {
		return nil, false
	}
	return o.EventKey, true
}

// HasEventKey returns a boolean if a field has been set.
func (o *MetricListingRep) HasEventKey() bool {
	if o != nil && o.EventKey != nil {
		return true
	}

	return false
}

// SetEventKey gets a reference to the given string and assigns it to the EventKey field.
func (o *MetricListingRep) SetEventKey(v string) {
	o.EventKey = &v
}

func (o MetricListingRep) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["_id"] = o.Id
	}
	if o.Key != nil {
		toSerialize["key"] = o.Key
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Kind != nil {
		toSerialize["kind"] = o.Kind
	}
	if o.AttachedFlagCount != nil {
		toSerialize["_attachedFlagCount"] = o.AttachedFlagCount
	}
	if o.Links != nil {
		toSerialize["_links"] = o.Links
	}
	if o.Site != nil {
		toSerialize["_site"] = o.Site
	}
	if o.Access != nil {
		toSerialize["_access"] = o.Access
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.CreationDate != nil {
		toSerialize["_creationDate"] = o.CreationDate
	}
	if o.LastModified != nil {
		toSerialize["lastModified"] = o.LastModified
	}
	if o.MaintainerId != nil {
		toSerialize["maintainerId"] = o.MaintainerId
	}
	if o.Maintainer != nil {
		toSerialize["_maintainer"] = o.Maintainer
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.IsNumeric != nil {
		toSerialize["isNumeric"] = o.IsNumeric
	}
	if o.SuccessCriteria != nil {
		toSerialize["successCriteria"] = o.SuccessCriteria
	}
	if o.Unit != nil {
		toSerialize["unit"] = o.Unit
	}
	if o.EventKey != nil {
		toSerialize["eventKey"] = o.EventKey
	}
	return json.Marshal(toSerialize)
}

type NullableMetricListingRep struct {
	value *MetricListingRep
	isSet bool
}

func (v NullableMetricListingRep) Get() *MetricListingRep {
	return v.value
}

func (v *NullableMetricListingRep) Set(val *MetricListingRep) {
	v.value = val
	v.isSet = true
}

func (v NullableMetricListingRep) IsSet() bool {
	return v.isSet
}

func (v *NullableMetricListingRep) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetricListingRep(val *MetricListingRep) *NullableMetricListingRep {
	return &NullableMetricListingRep{value: val, isSet: true}
}

func (v NullableMetricListingRep) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetricListingRep) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


