/*
 * LaunchDarkly REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0
 * Contact: support@launchdarkly.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ldapi

import (
	"encoding/json"
)

// ApiBranchCollectionRepItems struct for ApiBranchCollectionRepItems
type ApiBranchCollectionRepItems struct {
	Name *string `json:"name,omitempty"`
	Head *string `json:"head,omitempty"`
	UpdateSequenceId *int64 `json:"updateSequenceId,omitempty"`
	SyncTime *int64 `json:"syncTime,omitempty"`
	References *[]ApiBranchCollectionRepReferences `json:"references,omitempty"`
	Links *map[string]interface{} `json:"_links,omitempty"`
}

// NewApiBranchCollectionRepItems instantiates a new ApiBranchCollectionRepItems object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiBranchCollectionRepItems() *ApiBranchCollectionRepItems {
	this := ApiBranchCollectionRepItems{}
	return &this
}

// NewApiBranchCollectionRepItemsWithDefaults instantiates a new ApiBranchCollectionRepItems object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiBranchCollectionRepItemsWithDefaults() *ApiBranchCollectionRepItems {
	this := ApiBranchCollectionRepItems{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApiBranchCollectionRepItems) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBranchCollectionRepItems) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApiBranchCollectionRepItems) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApiBranchCollectionRepItems) SetName(v string) {
	o.Name = &v
}

// GetHead returns the Head field value if set, zero value otherwise.
func (o *ApiBranchCollectionRepItems) GetHead() string {
	if o == nil || o.Head == nil {
		var ret string
		return ret
	}
	return *o.Head
}

// GetHeadOk returns a tuple with the Head field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBranchCollectionRepItems) GetHeadOk() (*string, bool) {
	if o == nil || o.Head == nil {
		return nil, false
	}
	return o.Head, true
}

// HasHead returns a boolean if a field has been set.
func (o *ApiBranchCollectionRepItems) HasHead() bool {
	if o != nil && o.Head != nil {
		return true
	}

	return false
}

// SetHead gets a reference to the given string and assigns it to the Head field.
func (o *ApiBranchCollectionRepItems) SetHead(v string) {
	o.Head = &v
}

// GetUpdateSequenceId returns the UpdateSequenceId field value if set, zero value otherwise.
func (o *ApiBranchCollectionRepItems) GetUpdateSequenceId() int64 {
	if o == nil || o.UpdateSequenceId == nil {
		var ret int64
		return ret
	}
	return *o.UpdateSequenceId
}

// GetUpdateSequenceIdOk returns a tuple with the UpdateSequenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBranchCollectionRepItems) GetUpdateSequenceIdOk() (*int64, bool) {
	if o == nil || o.UpdateSequenceId == nil {
		return nil, false
	}
	return o.UpdateSequenceId, true
}

// HasUpdateSequenceId returns a boolean if a field has been set.
func (o *ApiBranchCollectionRepItems) HasUpdateSequenceId() bool {
	if o != nil && o.UpdateSequenceId != nil {
		return true
	}

	return false
}

// SetUpdateSequenceId gets a reference to the given int64 and assigns it to the UpdateSequenceId field.
func (o *ApiBranchCollectionRepItems) SetUpdateSequenceId(v int64) {
	o.UpdateSequenceId = &v
}

// GetSyncTime returns the SyncTime field value if set, zero value otherwise.
func (o *ApiBranchCollectionRepItems) GetSyncTime() int64 {
	if o == nil || o.SyncTime == nil {
		var ret int64
		return ret
	}
	return *o.SyncTime
}

// GetSyncTimeOk returns a tuple with the SyncTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBranchCollectionRepItems) GetSyncTimeOk() (*int64, bool) {
	if o == nil || o.SyncTime == nil {
		return nil, false
	}
	return o.SyncTime, true
}

// HasSyncTime returns a boolean if a field has been set.
func (o *ApiBranchCollectionRepItems) HasSyncTime() bool {
	if o != nil && o.SyncTime != nil {
		return true
	}

	return false
}

// SetSyncTime gets a reference to the given int64 and assigns it to the SyncTime field.
func (o *ApiBranchCollectionRepItems) SetSyncTime(v int64) {
	o.SyncTime = &v
}

// GetReferences returns the References field value if set, zero value otherwise.
func (o *ApiBranchCollectionRepItems) GetReferences() []ApiBranchCollectionRepReferences {
	if o == nil || o.References == nil {
		var ret []ApiBranchCollectionRepReferences
		return ret
	}
	return *o.References
}

// GetReferencesOk returns a tuple with the References field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBranchCollectionRepItems) GetReferencesOk() (*[]ApiBranchCollectionRepReferences, bool) {
	if o == nil || o.References == nil {
		return nil, false
	}
	return o.References, true
}

// HasReferences returns a boolean if a field has been set.
func (o *ApiBranchCollectionRepItems) HasReferences() bool {
	if o != nil && o.References != nil {
		return true
	}

	return false
}

// SetReferences gets a reference to the given []ApiBranchCollectionRepReferences and assigns it to the References field.
func (o *ApiBranchCollectionRepItems) SetReferences(v []ApiBranchCollectionRepReferences) {
	o.References = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *ApiBranchCollectionRepItems) GetLinks() map[string]interface{} {
	if o == nil || o.Links == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBranchCollectionRepItems) GetLinksOk() (*map[string]interface{}, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *ApiBranchCollectionRepItems) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given map[string]interface{} and assigns it to the Links field.
func (o *ApiBranchCollectionRepItems) SetLinks(v map[string]interface{}) {
	o.Links = &v
}

func (o ApiBranchCollectionRepItems) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Head != nil {
		toSerialize["head"] = o.Head
	}
	if o.UpdateSequenceId != nil {
		toSerialize["updateSequenceId"] = o.UpdateSequenceId
	}
	if o.SyncTime != nil {
		toSerialize["syncTime"] = o.SyncTime
	}
	if o.References != nil {
		toSerialize["references"] = o.References
	}
	if o.Links != nil {
		toSerialize["_links"] = o.Links
	}
	return json.Marshal(toSerialize)
}

type NullableApiBranchCollectionRepItems struct {
	value *ApiBranchCollectionRepItems
	isSet bool
}

func (v NullableApiBranchCollectionRepItems) Get() *ApiBranchCollectionRepItems {
	return v.value
}

func (v *NullableApiBranchCollectionRepItems) Set(val *ApiBranchCollectionRepItems) {
	v.value = val
	v.isSet = true
}

func (v NullableApiBranchCollectionRepItems) IsSet() bool {
	return v.isSet
}

func (v *NullableApiBranchCollectionRepItems) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiBranchCollectionRepItems(val *ApiBranchCollectionRepItems) *NullableApiBranchCollectionRepItems {
	return &NullableApiBranchCollectionRepItems{value: val, isSet: true}
}

func (v NullableApiBranchCollectionRepItems) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiBranchCollectionRepItems) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


